Debug test result path error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -160,6 +160,16 @@ runs:
         fi
         
         if [ -n "${{ inputs.testResultPath }}" ]; then
+          echo "${{ inputs.testResultPath }}"
+          if [ "${{ inputs.testResultPath }}" = *[!\ ]*  ]; then
+            echo " Fail 1";exit 1;
+          fi
+          if [[ "${{ inputs.testResultPath }}" = *[\?\"\*\<\>\|]*  ]]; then
+            echo " Fail 2";exit 1;
+          fi
+          if [[ "${{ inputs.testResultPath }}" != *.xml ]]; then
+            echo " Fail 3";exit 1;
+          fi
           if [ "${{ inputs.testResultPath }}" = *[!\ ]*  ] || [[ "${{ inputs.testResultPath }}" = *[\?\"\*\<\>\|]*  ]] || [[ "${{ inputs.testResultPath }}" != *.xml ]]; then
             echo "Error: Invalid Test Result Path";  exit 1; 
           fi
