Update error message

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -171,7 +171,7 @@ runs:
         elif [ -z "${{ inputs.testConfigName }}" -a -z "${{ inputs.suiteName }}" ]
           COMMANDSTR="scriptbased ${{ inputs.serverURL }} --test-config-name=${{ inputs.testConfigName }} --suite-name=${{ inputs.suiteName }}"
         else
-          echo "Error: Invalid test config info. Test Config ID or Test Config Name and Model Name / Suite Name must be provided.";  exit 1; 
+          echo "Error: Invalid test config info. Use testConfigId or testConfigName with only suiteName or modelName to continue.";  exit 1; 
         fi
 
         COMMANDSTR+="--client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --test-environment-timeout=${{ inputs.testEnvironmentTimeout }} --log-level=${{ inputs.logLevel }}"
