Add input handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -163,7 +163,18 @@ runs:
       run: |
         [[ "${{ inputs.serverURL }}" ]] || { echo "Error: Missing server URL" ; exit 1; }
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
-        COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }} --client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --test-environment-timeout=${{ inputs.testEnvironmentTimeout }} --log-level=${{ inputs.logLevel }}"
+        
+        if [ -z "${{ inputs.testConfigID }}" ]; then
+          COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }}"
+        elif [ -z "${{ inputs.testConfigName }}" -a -z "${{ inputs.modelName }}" ]
+          COMMANDSTR="modelbased ${{ inputs.serverURL }} --test-config-name=${{ inputs.testConfigName }} --model-name=${{ inputs.modelName }}" 
+        elif [ -z "${{ inputs.testConfigName }}" -a -z "${{ inputs.suiteName }}" ]
+          COMMANDSTR="scriptbased ${{ inputs.serverURL }} --test-config-name=${{ inputs.testConfigName }} --suite-name=${{ inputs.suiteName }}"
+        else
+          echo "Error: Invalid test config info. Test Config ID or Test Config Name and Model Name / Suite Name must be provided.";  exit 1; 
+        fi
+
+        COMMANDSTR+="--client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --test-environment-timeout=${{ inputs.testEnvironmentTimeout }} --log-level=${{ inputs.logLevel }}"
 
         if [ -n "${{ inputs.CACertPath }}" ]; then
           if [ ! -e "${{ inputs.CACertPath }}" ]; then
