Added empty and empty spaces checking

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -98,6 +98,8 @@ runs:
       run: |
         [[ "${{ inputs.serverURL }}" ]] || { echo "Error: Missing server URL" ; exit 1; }
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
+        [[ "${{ inputs.testResultPath }}" ]] || { echo "Error: Missing test result path" ; exit 1; }
+        [[ "${{ inputs.testResultPath }}" = *[!\ ]*  ]] || { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
         COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }} --client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --log-level=${{ inputs.logLevel }}"
         
         if [ -n "${{ inputs.CACertPath }}" ]; then
@@ -115,3 +117,4 @@ runs:
         echo "Executing: ./$CLI_FILENAME $COMMANDSTR"
         ./$CLI_FILENAME $COMMANDSTR
       shell: bash
+
