Update DAI version support 25.2

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,6 +54,15 @@ inputs:
   parameters:
     description: "The global parameter(s) to override in the format parameter_name=parameter_value"
     required: false
+  parametersFilePath:
+    description: "The path to a user-created JSON file that contains the global parameters you want to override"
+    required: false
+  filterBy:
+    description: "The filter to execute specific step within a test configuration in the form of filter_name=filter_value"
+    required: false
+  filterByJson:
+    description: "The path to a user-created JSON file that contains all the filters to execute specific steps within a test configuration"
+    required: false
   dryRun:
     description: "Perform a dry run only"
     required: false
@@ -179,6 +188,7 @@ runs:
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
         echo "serverURL=${{ inputs.serverURL }}"
         
+        # serverURL, testConfigID, testConfigName, modelName, suiteName
         if [[ -n "${{ inputs.testConfigID }}" ]]; then
           echo "testConfigID=${{ inputs.testConfigID }}"
           COMMANDARGS=("${{ inputs.serverURL }}" "${{ inputs.testConfigID }}")
@@ -203,12 +213,15 @@ runs:
         
         echo "Test config data validation complete."
         
-         if [ -n "${{ inputs.clientID }}" ]; then
+        # clientID
+        if [ -n "${{ inputs.clientID }}" ]; then
           COMMANDARGS+=("--client-id=${{ inputs.clientID }}")
-         fi
-          
+        fi
+        
+        # requestTimeout, requestRetries, backoffFactor, logLevel
         COMMANDARGS+=("--request-timeout=${{ inputs.requestTimeout }}" "--request-retries=${{ inputs.requestRetries }}" "--backoff-factor=${{ inputs.backoffFactor }}" "--log-level=${{ inputs.logLevel }}")
 
+        # CACertPath
         if [ -n "${{ inputs.CACertPath }}" ]; then
           if [ ! -e "${{ inputs.CACertPath }}" ]; then
             echo "Error: Invalid CA Cert Path";  exit 1; 
@@ -216,6 +229,7 @@ runs:
           COMMANDARGS+=("--ca-cert-path=${{ inputs.CACertPath }}")
         fi
         
+        # testResultPath
         if [ -n "${{ inputs.testResultPath }}" ]; then
           if [ "${{ inputs.testResultPath }}" = *[!\ ]*  ] || [[ "${{ inputs.testResultPath }}" = *[\?\"\*\<\>\|]*  ]] || [[ "${{ inputs.testResultPath }}" != *.xml ]]; then
             echo "Error: Invalid Test Result Path";  exit 1; 
@@ -223,10 +237,12 @@ runs:
           COMMANDARGS+=("--test-result-path=${{ inputs.testResultPath }}")
         fi
 
+        # dryRun
         if [ ${{ inputs.dryRun }} == true ]; then
           COMMANDARGS+=("--dry-run")
         fi
         
+        # parameters
         if [ -n "${{ inputs.parameters}}" ]; then
           IFS=';;' read -ra values <<< "${{ inputs.parameters }}"
           for value in "${values[@]}"; do
@@ -235,6 +251,33 @@ runs:
               COMMANDARGS+=("$value")
             fi
           done
+        fi
+
+        # parametersFilePath
+        if [ -n "${{ inputs.parametersFilePath }}" ]; then
+          if [ ! -e "${{ inputs.parametersFilePath }}" ]; then
+            echo "Error: Invalid overridden parameters file path";  exit 1; 
+          fi
+          COMMANDARGS+=("--param-file=${{ inputs.parametersFilePath }}")
+        fi
+        
+        # filterBy
+        if [ -n "${{ inputs.filterBy}}" ]; then
+          IFS=';;' read -ra values <<< "${{ inputs.filterBy }}"
+          for value in "${values[@]}"; do
+            if [ -n "$value" ]; then
+              COMMANDARGS+=("--filter-by")
+              COMMANDARGS+=("$value")
+            fi
+          done
+        fi
+
+        # filterByJson
+        if [ -n "${{ inputs.filterByJson }}" ]; then
+          if [ ! -e "${{ inputs.filterByJson }}" ]; then
+            echo "Error: Invalid test config step filters file path";  exit 1; 
+          fi
+          COMMANDARGS+=("--filter-by-json=${{ inputs.filterByJson }}")
         fi
 
         echo "Executing: $CLI_PATH ${COMMANDARGS[@]}"
